Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2023-11, with the labels that each got.

#78 Реворк БТРа
  code/game/supplyshuttle.dm
  code/game/turfs/open.dm
  code/modules/vehicles/apc/apc.dm
  maps/interiors/apc.dmm
Labels: Mapping, Feature, Balance, Needs Testing, Test Merge Only

#136 Make HPR Great! pt.2
  code/modules/projectiles/guns/rifles.dm
Labels: Balance, Needs Testing, Testmerge Candidate

#143 Shiva's Snowball
  code/game/turfs/auto_turf.dm
  code/modules/clothing/head/helmet.dm
  map_config/maps.txt
  maps/shivas_snowball.json
Labels: Mapping, Balance, Do Not Merge, Needs Testing, Testmerge Candidate

#132 Возращение Баррел Чарджера
  code/game/machinery/vending/vendor_types/requisitions.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
Labels: Balance, Testmerge Candidate
