Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2023-09, with the labels that each got.

#24 Санкен, но красивее
  fray-marines/icons/obj/structures/alien/Buildings.dmi
Labels: Sprites

#26 Map fixes
  maps/map_files/USS_Almayer/USS_Almayer.dmm
Labels: Mapping

#33 Sunken Update
  fray-marines/modules/cm_aliens/structures/special_structure.dm
  fray-marines/modules/mob/living/carbon/xenomorph/resin_constructions.dm
Labels: Balance

#38 Tests fixes
  fray-marines/code/modules/vehicles/hardpoints_walker.dm
  maps/map_files/USS_Almayer/USS_Almayer.dmm
Labels: Mapping, Fix, Sprites

#40 Timelocks change
  code/game/jobs/job/antag/xeno/queen.dm
  code/game/jobs/job/civilians/other/liaison.dm
  code/game/jobs/job/civilians/other/reporter.dm
  code/game/jobs/job/civilians/other/survivors.dm
  code/game/jobs/job/civilians/support/cmo.dm
  code/game/jobs/job/civilians/support/researcher.dm
  code/game/jobs/job/command/auxiliary/auxiliary_support_officer.dm
  code/game/jobs/job/command/auxiliary/crew_chief.dm
  code/game/jobs/job/command/auxiliary/intel.dm
  code/game/jobs/job/command/auxiliary/pilot.dm
  code/game/jobs/job/command/auxiliary/senior.dm
  code/game/jobs/job/command/auxiliary/tankcrew.dm
  code/game/jobs/job/command/cic/executive.dm
  code/game/jobs/job/command/cic/staffofficer.dm
  code/game/jobs/job/command/police/chief_police.dm
  code/game/jobs/job/command/police/police.dm
  code/game/jobs/job/command/police/warden.dm
  code/game/jobs/job/logistics/cargo/chief_req.dm
  code/game/jobs/job/logistics/engi/chief_engineer.dm
  code/game/jobs/job/marine/squad/leader.dm
  code/game/jobs/job/marine/squad/medic.dm
  code/game/jobs/job/marine/squad/smartgunner.dm
  code/game/jobs/job/marine/squad/specialist.dm
  code/game/jobs/job/marine/squad/tl.dm
Labels: Balance

#46 Обнова набора молотоспека
  code/modules/cm_marines/equipment/kit_boxes.dm
Labels: Balance

#47 переводы
  code/controllers/subsystem/ticker.dm
  code/datums/emergency_calls/big_game_hunter.dm
  code/datums/emergency_calls/cmb.dm
  code/datums/emergency_calls/contractor.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/dutch.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/feral_xenos.dm
  code/datums/emergency_calls/goons.dm
  code/datums/emergency_calls/hefa_knight.dm
  code/datums/emergency_calls/mercs.dm
  code/datums/emergency_calls/pirates.dm
  code/datums/emergency_calls/pizza.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/supplies.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/xenos.dm
  code/datums/statistics/random_facts/random_fact.dm
  code/game/gamemodes/cm_process.dm
  code/game/gamemodes/cm_self_destruct.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/game/gamemodes/colonialmarines/xenovsxeno.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/tabs/server_tab.dm
Labels: Grammar and Formatting

#49 [Говномёт ---> Огнемёт]
  code/modules/vehicles/hardpoints/hardpoint_ammo/primary_flamer_ammo.dm
  code/modules/vehicles/hardpoints/primary/flamer.dm
  colonialmarines.dme
  fray-marines/code/modules/projectiles/ammo_datums.dm
Labels: Feature, Balance

#51 epic embed fail
  code/modules/projectiles/gun_helpers.dm
  fray-marines/code/game/objects/items/weapons/st_equip.dm
Labels: Fix

#50 ахуй
  code/datums/supply_packs/vehicle_ammo.dm
  code/game/machinery/vending/vendor_types/crew/vehicle_crew.dm
  code/modules/vehicles/apc/apc.dm
  code/modules/vehicles/tank/tank.dm
  colonialmarines.dme
  fray-marines/code/game/objects/items/weapons/st_equip.dm
  fray-marines/code/modules/cm_aliens/structures/lessers_burrow.dm
  fray-marines/code/modules/cm_aliens/structures/special_structure.dm
  fray-marines/code/modules/gear_presets/usmc.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/Abilities.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/resin_constructions.dm
  fray-marines/code/modules/mob/living/simple_animal/hostile/alien.dm
  fray-marines/code/modules/mob/living/simple_animal/hostile/alien/tearer.dm
  fray-marines/code/modules/mob/living/simple_animal/hostile/alien/trooper.dm
  fray-marines/code/modules/vehicles/hardpoints/holder/tank_turret.dm
  fray-marines/code/modules/vehicles/hardpoints/support/smoke.dm
Labels: Feature, Code Improvement

#57 Return some sunken functionality
  code/_globalvars/global_lists.dm
  fray-marines/code/modules/cm_aliens/structures/special_structure.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/resin_constructions.dm
Labels: Merge Conflict, Balance

#58 Спрайтеки для СТшника, которые были стёрты
  fray-marines/code/game/objects/items/weapons/st_equip.dm
  fray-marines/icons/mob/human/back.dmi
  fray-marines/icons/mob/human/items_lefthand_1.dmi
  fray-marines/icons/mob/human/items_righthand_1.dmi
  fray-marines/icons/mob/human/st_equip.dmi
  icons/obj/items/storage.dmi
Labels: Sprites

#56 а вот и нёрф
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  fray-marines/code/__DEFINES/xeno.dm
Labels: Balance

#63 Fix borked obj paths
  fray-marines/code/modules/cm_aliens/structures/lessers_burrow.dm
  fray-marines/code/modules/cm_aliens/structures/special_structure.dm
  fray-marines/code/modules/mob/living/simple_animal/hostile/alien.dm
  fray-marines/code/modules/vehicles/hardpoints/holder/tank_turret.dm
  fray-marines/code/modules/vehicles/hardpoints/support/smoke.dm
  fray-marines/code/modules/vehicles/hardpoints_walker.dm
  fray-marines/code/modules/vehicles/walker.dm
Labels: Fix

#60 бика ОД ревёрт и урон давки техникой по стенам
  code/__DEFINES/chemistry.dm
  code/datums/effects/bleeding.dm
  code/modules/vehicles/apc/apc.dm
  code/modules/vehicles/tank/tank.dm
Labels: Feature, Balance

#54 Меха
  code/modules/mob/living/carbon/xenomorph/castes/Crusher.dm
  fray-marines/code/game/jobs/command/auxiliary/mech_crew.dm
  fray-marines/code/modules/gear_presets/usmc.dm
  fray-marines/code/modules/vehicles/hardpoints_walker.dm
  fray-marines/code/modules/vehicles/walker.dm
  fray-marines/code/modules/vehicles/walker_vendor.dm
  fray-marines/icons/obj/vehicles/mech-walker.dmi
  fray-marines/icons/obj/vehicles/mech.dmi
  fray-marines/icons/obj/vehicles/mecha_guns.dmi
Labels: Feature

#65 Разнофиксы
  code/modules/projectiles/ammo_datums.dm
  fray-marines/code/game/objects/items/weapons/st_equip.dm
  fray-marines/code/game/objects/items/weapons/st_hammer_stacks.dm
Labels: Fix, Balance, Refactor

#68 Debuff to burrow
  fray-marines/code/__DEFINES/xeno.dm
  fray-marines/code/modules/cm_aliens/structures/lessers_burrow.dm
Labels: Balance

#71 меха
  fray-marines/code/cm_tech/techs/marine/tier2/walker.dm
  fray-marines/code/modules/gear_presets/usmc.dm
  fray-marines/code/modules/vehicles/hardpoints_walker.dm
  fray-marines/code/modules/vehicles/walker.dm
  fray-marines/code/modules/vehicles/walker_vendor.dm
Labels: Feature

#67 фикс дальности стрельбы ТОВа
  code/modules/vehicles/hardpoints/hardpoint_ammo/tow_ammo.dm
  fray-marines/code/modules/projectiles/ammo_datums.dm
Labels: Fix

#61 Баф м44 револьвера. (магнум каким он должен быть)
  code/modules/projectiles/ammo_datums.dm
Labels: Feature

#79 Чиним линтер [ci skip]
  fray-marines/icons/obj/vehicles/mech.dmi
  fray-marines/icons/obj/vehicles/mecha_guns.dmi
  fray-marines/test/test.txt
Labels: Fix

#77 Логотип корпорации 'Вейлонда' -> 'В-Ю' для факсов
  code/modules/admin/fax_templates.dm
Labels: Fix

#75 99 патронов в мк1 магазинах вместо 95
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance

#69 Обновленные спрайты ксеноботов
  fray-marines/icons/mob/xenos/lesser_xeno.dmi
  fray-marines/icons/mob/xenos/lesser_xeno_big.dmi
Labels: Sprites

#81 Fix TOW ammo req
  code/datums/supply_packs/vehicle_ammo.dm
Labels: Fix

#66 фиксы ксеноботиков в 3 часа ночи
  fray-marines/code/modules/mob/living/simple_animal/hostile/alien.dm
Labels: Fix

#83 Фикс интела на фиорине, ремап мехбэя, уголок меха на аламо и нормандии.
  fray-marines/icons/obj/structures/machinery/mech_vendor.dmi
  maps/map_files/FOP_v2_Cellblocks/Prison_Station_FOP.dmm
  maps/map_files/USS_Almayer/USS_Almayer.dmm
  maps/shuttles/dropship_alamo.dmm
  maps/shuttles/dropship_normandy.dmm
Labels: Mapping, Sprites

#91 Map fix
  html/changelogs/archive/2023-09.yml
  maps/map_files/LV624/standalone/clfship.dmm
Labels: Mapping

#84 Попытка пофиксить """Фоторужьё""" [готово к мержу]
  code/game/machinery/vending/vending_types.dm
  code/modules/mob/living/carbon/xenomorph/castes/Burrower.dm
  code/modules/mob/living/carbon/xenomorph/castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/Hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
  code/modules/paperwork/photography.dm
Labels: Fix, Removal

#92 Spit on CO face
  code/game/machinery/vending/vendor_types/crew/synthetic.dm
  code/modules/mob/living/carbon/human/emote.dm
  sound/misc/spitemote.ogg
Labels: Sound
