Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2023-10, with the labels that each got.

#86 Прокачка станций обслуживания синтетиков
  code/game/machinery/rechargestation.dm
  colonialmarines.dme
  fray-marines/code/game/machinery/rechargestation.dm
Labels: Feature, Quality of Life, Do Not Merge, Good First PR, Needs Testing, Test Merge Only

#103 адекватные отжимания
  code/modules/mob/living/carbon/human/exercise.dm
Labels: Quality of Life, Testmerge Candidate

#104 Ремейк санки и QoL керриера [мержконфликт с ПРом течвебов]
  code/__DEFINES/xeno.dm
  code/_globalvars/global_lists.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_aliens/structures/special/egg_morpher.dm
  code/modules/mob/living/carbon/xenomorph/castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  colonialmarines.dme
  fray-marines/code/modules/cm_aliens/structures/special_structure.dm
  fray-marines/code/modules/cm_aliens/structures/sunken_colony.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/resin_constructions.dm
  fray-marines/icons/obj/structures/alien/Buildings.dmi
  fray-marines/icons/obj/structures/alien/effects.dmi
  fray-marines/sound/effects/burrower_attack1.ogg
Labels: Fix, Sprites, Sound, Balance, Refactor, Quality of Life, Balance Approved, Sprites Approved

#107 чачка фиксов
  code/game/objects/structures/blocker.dm
  code/modules/mob/living/carbon/xenomorph/egg_item.dm
  code/modules/mob/living/carbon/xenomorph/mutators/strains/carrier/eggsac.dm
  code/modules/projectiles/gun.dm
  code/modules/vehicles/hardpoints/armor/snowplow.dm
Labels: Fix, Balance, Removal, Balance Approved

#110 #TESTMERGE [Карта] #96 Алмайер
  code/game/area/almayer.dm
  icons/turf/area_almayer.dmi
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping, Sprites, Code Improvement

#114 (Минор Апдейт) Прически и Эмоуты Алмайерского обновления #96
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/new_player/sprite_accessories/hair.dm
  icons/mob/humans/human_hair.dmi
  sound/voice/human_female_cough_1.ogg
  sound/voice/human_female_cough_2.ogg
  sound/voice/human_female_gasp_1.ogg
  sound/voice/human_female_gasp_2.ogg
  sound/voice/human_female_laugh_1.ogg
  sound/voice/human_female_laugh_2.ogg
  sound/voice/human_male_cough_1.ogg
  sound/voice/human_male_cough_2.ogg
  sound/voice/human_male_gasp_1.ogg
  sound/voice/human_male_gasp_2.ogg
  sound/voice/human_male_gasp_3.ogg
  sound/voice/human_male_laugh_1.ogg
  sound/voice/human_male_laugh_2.ogg
Labels: Sprites, Sound, Code Improvement, Sprites Approved

#82 Возвращение легендарных течвебов
  code/__DEFINES/techtree.dm
  code/__DEFINES/xeno.dm
  code/datums/components/cluster_stack.dm
  code/game/machinery/telecomms/presets.dm
  code/game/machinery/vending/vendor_types/crew/sea.dm
  code/game/machinery/vending/vendor_types/crew/staff_officer.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_leader.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_specialist.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_tl.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/walls/r_wall.dm
  code/game/turfs/walls/walls.dm
  code/modules/cm_aliens/structures/special/pylon_core.dm
  code/modules/cm_tech/droppod/gear_access_point.dm
  code/modules/cm_tech/droppod/marine.dm
  code/modules/cm_tech/implements/armor.dm
  code/modules/cm_tech/implements/implants.dm
  code/modules/cm_tech/implements/rev_jelly.dm
  code/modules/cm_tech/tech_memories.dm
  code/modules/cm_tech/tech_tiers.dm
  code/modules/gear_presets/pmc.dm
  code/modules/mob/living/carbon/human/human_abilities.dm
  code/modules/mob/living/carbon/xenomorph/abilities/carrier/carrier_powers.dm
  code/modules/mob/living/carbon/xenomorph/abilities/queen/queen_abilities.dm
  code/modules/mob/living/carbon/xenomorph/abilities/queen/queen_powers.dm
  code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
  code/modules/objectives/communications.dm
  code/modules/objectives/data_retrieval.dm
  colonialmarines.dme
  fray-marines/code/cm_tech/comms_income.dm
  fray-marines/code/cm_tech/techs/abstract/item_droppod.dm
  fray-marines/code/cm_tech/techs/abstract/powerups_xeno.dm
  fray-marines/code/cm_tech/techs/abstract/tech_droppod.dm
  fray-marines/code/cm_tech/techs/abstract/tech_xeno.dm
  fray-marines/code/cm_tech/techs/abstract/transitory.dm
  fray-marines/code/cm_tech/techs/marine/tier1/engi_upgrade_mod.dm
  fray-marines/code/cm_tech/techs/marine/tier1/medic_upgrade_qol.dm
  fray-marines/code/cm_tech/techs/marine/tier1/mod_armor.dm
  fray-marines/code/cm_tech/techs/marine/tier2/enhanced_antibiologicals.dm
  fray-marines/code/cm_tech/techs/marine/tier2/tank.dm
  fray-marines/code/cm_tech/techs/marine/tier2/walker.dm
  fray-marines/code/cm_tech/techs/marine/tier3/combat_implants.dm
  fray-marines/code/cm_tech/techs/marine/tier3/experimentals.dm
  fray-marines/code/cm_tech/techs/xeno/tier1/blockade.dm
  fray-marines/code/cm_tech/techs/xeno/tier1/build_for_all.dm
  fray-marines/code/cm_tech/techs/xeno/tier1/comms_disruption.dm
  fray-marines/code/cm_tech/techs/xeno/tier2/evo_boost.dm
  fray-marines/code/cm_tech/techs/xeno/tier2/overshield.dm
  fray-marines/code/cm_tech/techs/xeno/tier2/shielding_slash.dm
  fray-marines/code/cm_tech/techs/xeno/tier2/teleport_beacon.dm
  fray-marines/code/cm_tech/techs/xeno/tier3/acid_blood.dm
  fray-marines/code/cm_tech/techs/xeno/tier3/artillery_blob.dm
  fray-marines/code/cm_tech/techs/xeno/tier3/rev_jelly.dm
  fray-marines/code/cm_tech/techtree.dm
  fray-marines/code/cm_tech/trees/xeno.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/queen_abilities.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/xeno_verbs.dm
  fray-marines/code/modules/projectiles/ammo_datums.dm
  fray-marines/code/modules/projectiles/magazines/magazines_assorted.dm
Labels: Feature, Fix, UI, Balance, Quality of Life, Balance Approved

#125 Runtime fixes
  code/global.dm
  code/modules/cm_marines/equipment/maps.dm
Labels: Server

#111 Music by Luci
  code/game/machinery/vending/vending_types.dm
  code/game/machinery/vending/vendor_types/general.dm
  code/game/objects/items/devices/walkman.dm
Labels: Feature, Testmerge Candidate

#112 Новые линзы ПНВ в карго!
  fray-marines/code/datums/supply_packs/gear.dm
Labels: Feature

#99 Make HPR meta again.
  code/datums/components/bonus_damage_stack.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance, Do Not Testmerge, Good First PR

#124 бафф пнв
  code/game/objects/items/devices/helmet_visors.dm
Labels: Balance

#119 багфиксы и мелкофичи
  code/modules/cm_aliens/structures/special/pylon_core.dm
  code/modules/cm_tech/techtree.dm
  code/modules/objectives/communications.dm
  code/modules/vehicles/hardpoints/armor/snowplow.dm
  fray-marines/code/cm_tech/comms_income.dm
Labels: Fix, Balance

#116 фичи пердаторов
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/yautja.dm
  code/controllers/subsystem/tracking.dm
  code/datums/elements/yautja_tracked_item.dm
  code/datums/keybinding/yautja.dm
  code/game/gamemodes/cm_initialize.dm
  code/modules/cm_preds/yaut_bracers.dm
  code/modules/cm_preds/yaut_hudprocs.dm
  code/modules/cm_preds/yaut_items.dm
  code/modules/cm_preds/yaut_mask.dm
  code/modules/cm_preds/yaut_mask_actions.dm
  code/modules/cm_preds/yaut_procs.dm
  code/modules/cm_preds/yaut_special_actions.dm
  code/modules/cm_preds/yaut_weapons.dm
  code/modules/mob/living/carbon/human/species/yautja/_species.dm
  code/modules/projectiles/ammo_datums.dm
  colonialmarines.dme
Labels: Feature, Fix, UI, Balance, Quality of Life, Balance Approved, Testmerge Candidate

#94 Динамические сквады
  code/game/jobs/job/marine/squads.dm
  code/game/jobs/role_authority.dm
Labels: enhancement, Feature, Balance, Quality of Life, Testmerge Candidate

#128 Lore-friendly synths, cargo turrets
  code/modules/gear_presets/synths.dm
  colonialmarines.dme
  fray-marines/code/datums/supply_packs/weapons.dm
Labels: Feature, Balance, Quality of Life, Needs Testing

#138 stormtroop v fray-marines
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  fray-marines/icons/mob/human/onmob/head_1.dmi
  fray-marines/icons/mob/human/onmob/suit_1.dmi
Labels: enhancement, Sprites, Refactor, Quality of Life, Priority: High

#137 Synths manufactures
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Feature

#113 Два новых стрейна для ксеноморфов [варриора мутатором обделили( ]
  code/__DEFINES/fray-marines/conflict.dm
  code/__DEFINES/fray-marines/mobs.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/mutators/strains/lurker/stalker.dm
  code/modules/mob/living/carbon/xenomorph/mutators/strains/spitter/suppressor.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/projectile.dm
  colonialmarines.dme
  fray-marines/code/modules/mob/living/carbon/xenomorph/abilities/boiler/boiler_abilities.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/abilities/spitter/spitter_abilities.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/abilities/spitter/spitter_powers.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/mutators.dm/behavior_delegate.dm
  fray-marines/code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  fray-marines/code/modules/mob/mod_defines.dm
  fray-marines/code/modules/projectiles/ammo_datums.dm
  icons/mob/xenos/spitter.dmi
Labels: Feature, Fix, Sprites, Sprites Approved, Testmerge Candidate
