Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2024-01, with the labels that each got.

#150 Кучка фиксов после мержа
  code/controllers/subsystem/vote.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  maps/map_files/generic/Admin_level.dmm
  maps/rumayer.json
Labels: Mapping, Fix, Balance, Grammar and Formatting, Removal

#147 Khami Barrens[MAP REVIVE]
  code/__DEFINES/__game.dm
  code/game/turfs/walls/wall_icon.dm
  code/modules/cm_marines/equipment/maps.dm
  colonialmarines.dme
  fray-marines/maps/doctoralex/KhamiBarrens/KhamiBarrens.dm
  icons/turf/ground_map.dmi
  map_config/maps.txt
  maps/khami_barrens.json
  maps/map_files/Khami_Barrens/Khami_Barrens.dmm
Labels: Mapping, Sprites

#145 Dock Red - сжимаем Биг Ред как можем
  code/__DEFINES/__game.dm
  code/modules/cm_marines/equipment/maps.dm
  code/modules/shuttle/dropship_hijack.dm
  colonialmarines.dme
  fray-marines/maps/doctoralex/Dock_Red/DR_areas.dm
  fray-marines/maps/doctoralex/hadleys_hope_wo.dmm
  map_config/maps.txt
  maps/dockred.json
  maps/map_files/Dock_Red/Dock_Red.dmm
Labels: Mapping, Merge Conflict

#149 Куча нововведений
  code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
  code/modules/character_traits/skills.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/xenomorph/abilities/lurker/lurker_powers.dm
Labels: Feature, Balance
