Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2024-04, with the labels that each got.

#161 SL-QoL
  code/game/machinery/vending/vendor_types/squad_prep/squad_leader.dm
Labels: Quality of Life

#151 Изменения и балансировка Док Реда
  fray-marines/maps/doctoralex/Dock_Red/DR_areas.dm
  maps/map_files/Dock_Red/Dock_Red.dmm
Labels: Mapping

#167 paperwork
  code/modules/admin/fax_templates.dm
Labels: Fix
