Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2025-08, with the labels that each got.

#498 rava_flame_reborn
  core_ru/code/modules/mob/living/carbon/xenomorph/strains/castes/ravager/flamethrower.dm
  core_ru/icons/mob/xenos/ravager.dmi
Labels: Feature, Sprites, Balance, size/M

#495 Revert "Warrior Boxer Strain (#327)"
  code/__DEFINES/core_defines_ru/xeno.dm
  colonialmarines.dme
  core_ru/code/includes.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_abilities.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_powers.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/castes/Warrior.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/strains/castes/warrior/boxer.dm
Labels: Removal, size/L

#471 Stuff for Fiorina №4
  code/__DEFINES/sounds.dm
  code/game/area/Prison_Station_FOP.dm
  code/game/area/Prison_Station_RU.dm
  colonialmarines.dme
  maps/map_files/FOP_v2_Cellblocks_RU/Prison_Station_FOP_RU.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/24.clearLZ1.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/30.lizards.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/40.destroyed_dining_room.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/43.contaimed_WY_lab.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/46.walls_exploded.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/50.no_CLF_ship.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/50.nocrates.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/60.vip_front.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/60.visitations_exploded.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/70.bp_ls.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/70.sci_rest_room.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/80.walls_exploded.dmm
  sound/ambience/prisonfopru/controlroomambience.ogg
  sound/ambience/prisonfopru/prisonalarm.ogg
  sound/ambience/prisonfopru/prisonalarm1.ogg
  sound/ambience/prisonfopru/prisonalarm2.ogg
  sound/ambience/prisonfopru/prisonalarm3.ogg
  sound/ambience/prisonfopru/prisonbridgeambience.ogg
  sound/ambience/prisonfopru/prisoncommon1.ogg
  sound/ambience/prisonfopru/prisoncommon2.ogg
  sound/ambience/prisonfopru/prisoncommon3.ogg
  sound/ambience/prisonfopru/prisoncommon4.ogg
  sound/ambience/prisonfopru/prisoncommon5.ogg
  sound/ambience/prisonfopru/prisoncomputer1.ogg
  sound/ambience/prisonfopru/prisoncomputer2.ogg
  sound/ambience/prisonfopru/prisoncomputer3.ogg
  sound/ambience/prisonfopru/prisonintercomseegson.ogg
  sound/ambience/prisonfopru/prisonmaintenancehalls2.ogg
  sound/ambience/prisonfopru/prisonmaintenancehalls3.ogg
  sound/ambience/prisonfopru/prisonmaintenancehalls4.ogg
  sound/ambience/prisonfopru/prisonstationmachines1.ogg
  sound/ambience/prisonfopru/prisonstationmachines2.ogg
  sound/ambience/prisonfopru/prisonstationmachines3.ogg
  sound/ambience/prisonfopru/prisonstationmachines4.ogg
  sound/ambience/prisonfopru/prisonstationmachines5.ogg
  sound/ambience/prisonfopru/prisonstationservers1.ogg
  sound/ambience/prisonfopru/prisonstationwaterdrop.ogg
Labels: Mapping, Sound, Code Improvement, Needs Testing, Testmerge Candidate, size/XXL

#489 SL helmet visor buff
  core_ru/code/modules/clothing/head/helmet.dm
Labels: Quality of Life, Stale Exempt, size/XS
