Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2025-01, with the labels that each got.

#297 Sunken colony for xeno
  code/modules/mob/living/carbon/xenomorph/hive_status.dm
  core_ru/code/modules/cm_aliens/structures/sunken_colony.dm
Labels: Feature

#313 squad leader pod drop
  code/game/machinery/vending/vendor_types/squad_prep/squad_leader.dm
  code/modules/mob/living/carbon/human/human_abilities.dm
  core_ru/code/game/objects/items/storage/backpack.dm
Labels: Feature

#327 Warrior Boxer Strain
  code/__DEFINES/core_defines_ru/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_powers.dm
  colonialmarines.dme
  core_ru/code/includes.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_abilities.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_macros.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_powers.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/castes/Warrior.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/strains/castes/warrior/boxer.dm
Labels: Feature

#328 Marines Buffs
  code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
  code/game/machinery/vending/vendor_types/requisitions.dm
  code/modules/clothing/glasses/night.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smartgun.dm
  core_ru/code/datums/ammo/bullet/special_ammo.dm
  core_ru/code/game/objects/items/storage/belt.dm
  core_ru/code/includes.dm
  core_ru/code/modules/clothing/glasses/night.dm
  core_ru/code/modules/cm_marines/equipment/weapons.dm
  core_ru/code/modules/cm_tech/techs/marine/tier1/engi_upgrade_mod.dm
  core_ru/code/modules/cm_tech/techs/marine/tier1/medic_upgrade_qol.dm
  core_ru/code/modules/cm_tech/techs/marine/tier3/experimentals.dm
  core_ru/code/modules/projectiles/gun_attachables.dm
  core_ru/code/modules/projectiles/guns/smartgun.dm
  core_ru/code/modules/projectiles/magazines/specialist.dm
Labels: Balance

#326 Queen Charger Strain
  code/__DEFINES/core_defines_ru/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities/general_abilities.dm
  code/modules/mob/living/carbon/xenomorph/strains/castes/crusher/charger.dm
  code/modules/mob/living/carbon/xenomorph/strains/castes/praetorian/warden.dm
  core_ru/code/includes.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/abilities/crusher/crusher_abilities.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/abilities/queen/queen_abilities.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/castes/Queen.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/strains/castes/queen/queen_charger.dm
Labels: Feature, Balance

#333 rolescal
  code/game/jobs/job/command/auxiliary/tank_crew.dm
  core_ru/code/game/jobs/job/command/auxiliary/mech_crew.dm
Labels: Feature

#331 RAV WITH FIRE!!! FIREEE!!!
  code/game/atoms.dm
  code/game/objects/objs.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_aliens/structures/egg.dm
  code/modules/cm_aliens/structures/fruit.dm
  code/modules/cm_aliens/structures/trap.dm
  code/modules/cm_aliens/weeds.dm
  code/modules/mob/living/carbon/human/life/handle_environment.dm
  code/modules/mob/living/carbon/human/life/handle_fire.dm
  code/modules/mob/living/carbon/xenomorph/castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/guns/flamer/flamer.dm
  code/modules/projectiles/guns/flamer/flameshape.dm
  code/modules/reagents/Chemistry-Reagents.dm
  core_ru/code/includes.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/abilities/warrior/warrior_macros.dm
  core_ru/code/modules/mob/living/carbon/xenomorph/strains/castes/ravager/flamethrower.dm
Labels: Feature, Stale Exempt, Testmerge Candidate

#334 Эвакуация корабля
  code/__DEFINES/core_defines_ru/mode.dm
  code/controllers/subsystem/hijack.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/ARES/ARES_interface.dm
  code/game/machinery/computer/almayer_control.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/shuttle/computers/dropship_computer.dm
  code/modules/shuttle/shuttles/dropship.dm
  core_ru/code/controllers/subsystem/hijack.dm
  core_ru/code/includes.dm
  tgui/packages/tgui/interfaces/AlmayerControl.jsx
  tgui/packages/tgui/interfaces/AresAdmin.jsx
  tgui/packages/tgui/interfaces/AresInterface.jsx
Labels: Feature, UI, Stale Exempt, Testmerge Candidate

#329 Breakable Xeno Armor
  code/datums/ammo/ammo.dm
  code/datums/ammo/bullet/pistol.dm
  code/datums/ammo/bullet/revolver.dm
  code/datums/ammo/bullet/rifle.dm
  code/datums/ammo/bullet/smg.dm
  code/datums/ammo/bullet/sniper.dm
  code/datums/ammo/bullet/special_ammo.dm
  code/datums/ammo/bullet/tank.dm
  code/datums/combat_personalized.dm
  code/datums/mob_hud.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/projectiles/gun.dm
  icons/mob/hud/hud.dmi
  tgui/packages/tgui/interfaces/WeaponStats.jsx
Labels: Feature, Sprites, UI, Stale Exempt, Testmerge Candidate

#337 Down CD for hunting grounds
  code/modules/cm_preds/yaut_items.dm
Labels: Quality of Life

#339 ST Fixes
  core_ru/code/game/objects/items/weapons/st_equip.dm
  core_ru/code/modules/clothing/head/helmet.dm
  core_ru/code/modules/clothing/suits/marine_armor/st_armor.dm
  core_ru/code/modules/projectiles/guns/rifles.dm
Labels: Fix
