Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2025-04, with the labels that each got.

#418 SmartWindows (for CIC) and Vehicle Elevator Animation
  code/game/objects/structures/window.dm
  code/modules/shuttle/vehicle_elevator.dm
  colonialmarines.dme
  core_ru/code/game/objects/effects/elevator.dm
  core_ru/code/game/objects/structures/window.dm
  core_ru/code/modules/shuttle/vehicle_elevator.dm
Labels: Missing Changelog

#422 Fix
  core_ru/code/modules/clothing/ranks.dm
  core_ru/icons/obj/items/clothing/ranks.dmi
Labels: Sprites, Missing Changelog

#362 New stuff for Fiorina №2
  maps/map_files/FOP_v2_Cellblocks_RU/Prison_Station_FOP_RU.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/30.lizards.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/40.destroyed_dining_room.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/43.contaimed_WY_lab.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/60.vip_front.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/60.visitations_exploded.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/70.bp_ls.dmm
  maps/map_files/FOP_v2_Cellblocks_RU/sprinkles/80.walls_exploded.dmm
  maps/prison_station_fop_ru.json
Labels: Mapping, Sprites, Sound, UI

#420 LV522 fix spawn
  map_config/maps.txt
  maps/lv522_chances_claim_ru.json
  maps/map_files/LV522_Chances_Claim_ru/LV522_Chances_Claim_ru.dmm
Labels: Mapping, Good First PR

#424 Runtimes fix RP
  code/controllers/subsystem/influxstats.dm
  core_ru/code/modules/vehicles/walker.dm
  core_ru/code/modules/vehicles/walker_verbs.dm
Labels: Fix

#426 Fix linters
  maps/map_files/LV522_Chances_Claim_ru/LV522_Chances_Claim_ru.dmm
Labels: Mapping, Missing Changelog

#417 Small fixes on Almayer_RU
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping

#413 Fix of stormtrooper sprites + new sprites
  core_ru/code/game/objects/items/storage/belt.dm
  core_ru/code/modules/projectiles/guns/rifles.dm
  core_ru/icons/mob/hud/actions.dmi
  core_ru/icons/mob/humans/onmob/items_lefthand_0.dmi
  core_ru/icons/mob/humans/onmob/items_righthand_0.dmi
  core_ru/icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi
  core_ru/icons/obj/items/weapons/weapons.dmi
Labels: Fix, Sprites, Stale

#425 Add Doctors and Engineers W-Y Goons
  code/datums/emergency_calls/goons.dm
Labels: Feature, Stale

#415 RU APC remap
  core_ru/code/game/machinery/computer/groundside_operations.dm
  core_ru/code/game/objects/structures/table_racks.dm
  core_ru/code/includes.dm
  core_ru/code/modules/almayer/machinery.dm
  core_ru/code/modules/cm_marines/overwatch.dm
  core_ru/code/modules/vehicles/interiors/interiors_landmarks.dm
  core_ru/code/modules/vehicles/multitile/apc/apc.dm
  core_ru/icons/obj/structures/machinery/toc.dmi
  core_ru/icons/obj/structures/tables.dmi
  core_ru/icons/obj/vehicles/interiors/general.dmi
  maps/interiors/apcru.dmm
Labels: Mapping, Sprites

#446 Some fixes
  code/modules/mob/living/carbon/xenomorph/hive_status.dm
  maps/map_files/LV624/LV624.dmm
Labels: Mapping, Fix

#436 mechnerf
  core_ru/code/modules/vehicles/hardpoints_walker.dm
Labels: Balance, Stale
