Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2025-05, with the labels that each got.

#441 New groundside console!
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping, Stale

#458 Mini CIC Fix
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping

#454 Возврат вещей - синтам
  code/game/machinery/vending/vendor_types/crew/synthetic.dm
Labels: Feature, Stale

#470 Hotfix rumayler
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping, Missing Changelog

#464 Renames "stormtrooper" spec to "breacher" spec
  code/__DEFINES/core_defines_ru/skills.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_specialist.dm
  core_ru/code/game/objects/items/weapons/breacher_equip.dm
  core_ru/code/game/objects/items/weapons/breacher_hammer_stacks.dm
  core_ru/code/includes.dm
  core_ru/code/modules/clothing/gloves/marine_gloves.dm
  core_ru/code/modules/clothing/head/helmet.dm
  core_ru/code/modules/clothing/suits/marine_armor/breacher_armor.dm
  core_ru/code/modules/cm_marines/equipment/kit_boxes.dm
  core_ru/code/modules/cm_marines/specialist.dm
  core_ru/code/modules/projectiles/guns/rifles.dm
  core_ru/icons/mob/hud/actions.dmi
  core_ru/icons/mob/humans/onmob/belt.dmi
  core_ru/icons/mob/humans/onmob/hands.dmi
  core_ru/icons/mob/humans/onmob/head_1.dmi
  core_ru/icons/mob/humans/onmob/items_lefthand_0.dmi
  core_ru/icons/mob/humans/onmob/items_righthand_0.dmi
  core_ru/icons/mob/humans/onmob/suit_slot.dmi
  core_ru/icons/obj/items/breacher_spec.dmi
  core_ru/icons/obj/items/clothing/gloves.dmi
  core_ru/icons/obj/items/storage.dmi
  core_ru/icons/obj/items/weapons/weapons.dmi
Labels: Sprites, Code Improvement, Stale, Quality of Life

#473 Fixes unacidable shutters in ARES core
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping
