Repository RU-CMSS13/RU-CMSS13, pull requests merged in 2025-03, with the labels that each got.

#350 oocfix
  code/game/verbs/ooc.dm
Labels: Missing Changelog

#352 sunken nerf
  core_ru/code/modules/cm_aliens/structures/sunken_colony.dm
Labels: Balance

#368 APC zone and telephone fix
  maps/interiors/apcru.dmm
Labels: Mapping

#349 Mech fix
  code/game/objects/structures/blocker.dm
Labels: Fix, Stale

#347 should fix queen trade
  core_ru/code/modules/mob/living/carbon/xenomorph/abilities/queen/queen_powers.dm
Labels: Fix, Stale

#359 Rumayer Update! (New lower medbay + ASO office)
  maps/map_files/USS_Almayer/USS_Almayer.dmm
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping

#360 Fixed yautja communicator
  code/game/machinery/telecomms/broadcaster.dm
Labels: Fix

#342 price fix io poncho
  code/game/machinery/vending/vendor_types/intelligence_officer.dm
Labels: Fix, Stale

#348 STALKER FOREVER!!!!!
  core_ru/code/modules/mob/living/carbon/xenomorph/strains/castes/lurker/stalker.dm
  core_ru/icons/mob/xenos/lurker.dmi
Labels: Feature, Sprites, Stale

#373 Sunken change pre-attack icon
  core_ru/code/modules/cm_aliens/structures/sunken_colony.dm
Labels: Quality of Life

#353 NO FUN DEFIBILATIONS ONLY UPSTREAM.
  code/game/machinery/recharger.dm
  code/game/machinery/vending/vendor_types/crew/synthetic.dm
  code/game/machinery/vending/vendor_types/squad_prep/squad_engineer.dm
  code/game/objects/items/devices/defibrillator.dm
  code/modules/cm_tech/implements/medical_czsp.dm
  core_ru/code/game/objects/items/devices/_defibrillator.dm
  core_ru/code/game/objects/items/devices/defibrillator_paddles.dm
  core_ru/code/includes.dm
  core_ru/icons/effects/beam.dmi
  core_ru/icons/obj/items/defibs.dmi
Labels: Sprites, Sound, Removal

#382 Mech double weapons fix
  core_ru/code/modules/vehicles/walker.dm
  core_ru/code/modules/vehicles/walker_vendor.dm
Labels: Fix

#376 Sunken main + impale new sprites
  core_ru/icons/obj/structures/alien/Buildings.dmi
  core_ru/icons/obj/structures/alien/effects.dmi
Labels: Sprites

#369 Revert armor punch
  code/datums/ammo/ammo.dm
  code/datums/ammo/bullet/pistol.dm
  code/datums/ammo/bullet/revolver.dm
  code/datums/ammo/bullet/rifle.dm
  code/datums/ammo/bullet/smg.dm
  code/datums/ammo/bullet/sniper.dm
  code/datums/ammo/bullet/special_ammo.dm
  code/datums/ammo/bullet/tank.dm
  code/datums/combat_personalized.dm
  code/datums/mob_hud.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/projectiles/gun.dm
  icons/mob/hud/hud.dmi
  tgui/packages/tgui/interfaces/WeaponStats.jsx
Labels: Feature, Sprites, UI, Removal

#386 Revert "Admins into SQUARE HOLE (DB) (#256)"
  code/__DEFINES/_idefinse_includes.dm
  code/__DEFINES/core_defines_ru/subsystems.dm
  code/controllers/subsystem/who.dm
  code/datums/entities/player.dm
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/holder2.dm
  code/modules/admin/tabs/debug_tab.dm
  code/modules/admin/topic/topic.dm
  code/modules/client/client_procs.dm
  core_ru/code/datums/entities/admins.dm
  core_ru/code/includes.dm
Labels: Code Improvement

#374 Return room driver control console in CL office and small fixes.
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping

#400 mech fix
  core_ru/code/modules/vehicles/walker.dm
  core_ru/code/modules/vehicles/walker_verbs.dm
  core_ru/code/modules/vehicles/walker_wm88_helper.dm
Labels: Missing Changelog

#399 Перевод авто-ответов для менторхелпов
  code/modules/admin/autoreply.dm
  core_ru/code/includes.dm
  core_ru/code/modules/admin/autoreply.dm
Labels: Quality of Life

#401 Deleting trashbags
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping

#403 Marine ranks
  core_ru/code/includes.dm
  core_ru/code/modules/clothing/ranks.dm
  core_ru/icons/mob/humans/onmob/onmob_ranks.dmi
  core_ru/icons/obj/items/clothing/ranks.dmi
Labels: Sprites

#405 CL briefcase test-fix PR
  code/game/objects/items/storage/secure.dm
Labels: Missing Changelog

#404 Another Almayer_RU Update!
  maps/map_files/USS_Almayer_RU/USS_Almayer_RU.dmm
Labels: Mapping

#402 Tank tech fix
  code/game/machinery/vending/vendor_types/crew/vehicle_crew.dm
  core_ru/code/game/jobs/job/command/auxiliary/tankcrew.dm
Labels: Fix

#406 Small fix marine ranks.
  core_ru/icons/mob/humans/onmob/onmob_ranks.dmi
Labels: Fix, Sprites
